// <auto-generated />
namespace BetizagastiGnocchi.BackEnd.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agregandomovimientosdezonas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregandomovimientosdezonas));
        
        string IMigrationMetadata.Id
        {
            get { return "201711181243340_agregando movimientos de zonas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
