// <auto-generated />
namespace BetizagastiGnocchi.BackEnd.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agregandohoraaMovimientozona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregandohoraaMovimientozona));
        
        string IMigrationMetadata.Id
        {
            get { return "201711181330118_agregando hora a Movimientozona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
